@extends('layouts.app')
@section('title','لوحة التحكم')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
 <div><div class="eyebrow">لوحة الإدارة الذكية</div><h1 class="page-title">مرحباً {{ auth()->user()->name }} 👋</h1><p class="text-muted mb-0 mt-2">{{ $facility ? $facility->name.' · '.$facility->typeLabel() : 'إدارة المخزون والمنشأة والأشخاص من مكان واحد.' }}</p></div>
 <div class="d-flex gap-2"><a href="{{ route('people.create') }}" class="btn btn-primary"><i class="bi bi-person-plus ms-2"></i>إضافة شخص</a><a href="{{ route('attendance.create') }}" class="btn btn-light"><i class="bi bi-clock-history ms-2"></i>تسجيل حضور</a></div>
</div>
<div class="row g-3 mb-4">
 @foreach([['المنتجات',$stats['products'],'bi-box-seam','blue',route('products.index')],['الأشخاص النشطون',$stats['people'],'bi-people','violet',route('people.index')],['حراس الأمن',$stats['guards'],'bi-shield-lock','green',route('people.index',['type'=>'security_guard'])],['الحاضرون اليوم',$stats['present'],'bi-person-check','orange',route('attendance.index')],['الغياب اليوم',$stats['absent'],'bi-person-x','red',route('attendance.index',['status'=>'absent'])],['الساعات الإضافية',sprintf('%02d:%02d',intdiv($stats['overtime'],60),$stats['overtime']%60),'bi-hourglass-split','indigo',route('attendance.index')],['قيمة المخزون',$stats['inventory_cost'],'bi-cash-stack','teal',route('products.index')],['الزوار',$stats['visitors'],'bi-person-vcard','pink',route('visitors.index')]] as $s)
 <div class="col-6 col-xl-3"><a href="{{ $s[4] }}" class="text-decoration-none"><div class="card stat-card h-100 p-3"><div class="d-flex justify-content-between"><span class="icon-box {{ $s[3] }}"><i class="bi {{ $s[2] }}"></i></span><i class="bi bi-arrow-up-left text-muted"></i></div><div class="mt-3 text-muted small">{{ $s[0] }}</div><div class="fs-4 fw-bold text-dark mt-1">{{ is_numeric($s[1]) && !in_array($s[0],['قيمة المخزون']) ? number_format($s[1]) : (is_numeric($s[1]) ? number_format($s[1],2) : $s[1]) }}</div></div></a></div>
 @endforeach
</div>
<div class="row g-4 mb-4">
 <div class="col-xl-8"><div class="card p-3 h-100"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1">حركة المخزون والحضور</h5><small class="text-muted">آخر 7 أيام</small></div><span class="badge bg-light text-dark">مباشر</span></div><canvas id="overviewChart" height="110"></canvas></div></div>
 <div class="col-xl-4"><div class="card h-100"><div class="card-header"><h5 class="fw-bold mb-1">ملخص مالي</h5><small class="text-muted">القيمة الحالية للمخزون</small></div><div class="p-3"><div class="metric-row"><span>تكلفة المخزون</span><strong>{{ number_format($stats['inventory_cost'],2) }}</strong></div><div class="metric-row"><span>القيمة البيعية</span><strong>{{ number_format($stats['inventory_retail'],2) }}</strong></div><div class="metric-row"><span>الربح المتوقع</span><strong class="text-success">{{ number_format($stats['expected_profit'],2) }}</strong></div><div class="progress mt-3" style="height:8px"><div class="progress-bar" style="width:{{ $stats['inventory_retail'] > 0 ? min(100,($stats['inventory_cost']/$stats['inventory_retail'])*100) : 0 }}%"></div></div></div></div></div>
</div>
<div class="row g-4">
 <div class="col-xl-7"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><div><h5 class="fw-bold mb-1">آخر حركات المخزون</h5><small class="text-muted">أحدث العمليات</small></div><a href="{{ route('stock-movements.index') }}" class="btn btn-sm btn-light">عرض الكل</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>المنتج</th><th>المستودع</th><th>النوع</th><th>الكمية</th><th>التاريخ</th></tr></thead><tbody>@forelse($recentMovements as $m)<tr><td><strong>{{ $m->product->name }}</strong><small class="d-block text-muted">{{ $m->product->sku }}</small></td><td>{{ $m->warehouse->name }}</td><td><span class="badge {{ $m->type==='in'?'bg-success-subtle text-success':($m->type==='out'?'bg-danger-subtle text-danger':'bg-warning-subtle text-warning-emphasis') }}">{{ $m->type==='in'?'وارد':($m->type==='out'?'صادر':'تسوية') }}</span></td><td class="fw-bold">{{ number_format($m->quantity) }}</td><td>{{ $m->created_at->format('Y/m/d') }}</td></tr>@empty<tr><td colspan="5" class="text-center py-5 text-muted">لا توجد حركات.</td></tr>@endforelse</tbody></table></div></div></div>
 <div class="col-xl-5"><div class="card h-100"><div class="card-header d-flex justify-content-between"><div><h5 class="fw-bold mb-1">تنبيهات المخزون</h5><small class="text-muted">تحتاج متابعة</small></div><span class="badge bg-danger-subtle text-danger">{{ $lowStockProducts->count() }}</span></div><div class="p-3">@forelse($lowStockProducts as $product)<a href="{{ route('products.show',$product) }}" class="d-flex justify-content-between align-items-center py-3 border-bottom text-decoration-none"><div><strong class="text-dark d-block">{{ $product->name }}</strong><small class="text-muted">{{ $product->sku }}</small></div><span class="text-danger fw-bold">{{ number_format($product->total_stock ?? 0) }}</span></a>@empty<div class="text-center py-5 text-success"><i class="bi bi-shield-check fs-2"></i><p class="mb-0 mt-2">المخزون بحالة جيدة</p></div>@endforelse</div></div></div>
</div>
@endsection
@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>new Chart(document.getElementById('overviewChart'),{type:'line',data:{labels:@json($chart->pluck('label')),datasets:[{label:'وارد',data:@json($chart->pluck('in')),tension:.35},{label:'صادر',data:@json($chart->pluck('out')),tension:.35},{label:'حضور',data:@json($chart->pluck('attendance')),tension:.35}]},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true}}}});</script>
@endsection
