@extends('layouts.app')
@section('title', __('Payment Verification'))
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><div class="eyebrow">{{ __('Payment Verification') }}</div><h1 class="page-title">#{{ $payment->id }} — {{ $payment->method->name }}</h1></div><a href="{{ route('payments.index') }}" class="btn btn-light">{{ __('Payment History') }}</a></div>
<div class="row g-4"><div class="col-lg-7"><div class="card p-4"><div class="row g-3"><div class="col-md-6"><span class="text-muted">{{ __('Amount') }}</span><h4>{{ number_format($payment->amount,2) }} {{ $payment->currency }}</h4></div><div class="col-md-6"><span class="text-muted">{{ __('Status') }}</span><h4><span class="badge text-bg-{{ $payment->status==='approved'?'success':($payment->status==='rejected'?'danger':'warning') }}">{{ $payment->status }}</span></h4></div><div class="col-md-6"><span class="text-muted">{{ __('Reference') }}</span><div>{{ $payment->reference ?: '—' }}</div></div><div class="col-md-6"><span class="text-muted">{{ __('Submitted by') }}</span><div>{{ $payment->submitter->name }}</div></div><div class="col-md-6"><span class="text-muted">{{ __('Payer Name') }}</span><div>{{ $payment->payer_name ?: '—' }}</div></div><div class="col-md-6"><span class="text-muted">{{ __('Payer Account') }}</span><div>{{ $payment->payer_account ?: '—' }}</div></div></div>@if($payment->review_notes)<hr><strong>{{ __('Review notes') }}</strong><p class="mb-0">{{ $payment->review_notes }}</p>@endif</div></div>
<div class="col-lg-5"><div class="card p-4"><h5 class="fw-bold mb-3">{{ __('Payment Receipt') }}</h5>@if($payment->receipt_path)<a href="{{ route('payments.receipt',$payment) }}" class="btn btn-outline-primary mb-3"><i class="bi bi-download"></i> {{ __('Download receipt') }}</a>@if(Str::endsWith(strtolower($payment->receipt_path), ['.jpg','.jpeg','.png','.webp']))<img src="{{ Storage::url($payment->receipt_path) }}" class="img-fluid rounded-3 border">@else<div class="alert alert-light">PDF receipt attached.</div>@endif
@endif</div>
@if(auth()->user()->isAdmin() && $payment->status === 'pending')<div class="card p-4 mt-4"><h5 class="fw-bold">{{ __('Review') }}</h5><form action="{{ route('payments.review',$payment) }}" method="POST">@csrf<div class="mb-3"><label class="form-label">{{ __('Review notes') }}</label><textarea name="review_notes" class="form-control" rows="3"></textarea></div><div class="d-flex gap-2"><button name="status" value="approved" class="btn btn-success">{{ __('Approve') }}</button><button name="status" value="rejected" class="btn btn-danger">{{ __('Reject') }}</button></div></form></div>@endif</div></div>
@endsection
